### ISSUE TITLE
Feature request: Save page to Wayback Machine and/or archive.today

### ISSUE THREAD

**Issue by immewnity** [themarshallproject/klaxon#610] opened 2023-01-09 15:12 UTC
It'd be super nifty to automatically archive any changed pages to the Wayback Machine or another archive site like archive.today . If time permits, I'll work on this, but wanted to post it here in case someone wants to do it first.

**Comment by tommeagher** [comment] 2023-12-18 20:21
Closing this as a duplicate of #436

**Closed by tommeagher** 2023-12-18 20:21 UTC
Labels: duplicate, wontfix
