### ISSUE TITLE
Unable to watch public facebook pages

### ISSUE THREAD

**Issue by bobweston** [themarshallproject/klaxon#112] opened 2017-05-09 20:58 UTC
The Governor of Missouri tends to use his public facebook page to make announcements.

https://www.facebook.com/EricGreitens/

We've tried watching the page. But Klaxon doesn't respond at all when trying to add a watch item on that page.

I'm unsure if this is in any way related to #83

But noting it here just in case.

**Comment by GabeIsman** [comment] 2017-05-11 19:30
Yea it looks like it's the same Content Security Policy issue. The workaround for now is to add the page manually from Klaxon. 

This is a duplicate of #84. Thanks for reporting @bobweston!

**Closed by GabeIsman** 2017-05-11 19:30 UTC
