### ISSUE TITLE
`rake check:all` not detecting changes reliably

### ISSUE THREAD

**Issue by myersjustinc** [themarshallproject/klaxon#17] opened 2016-05-03 18:57 UTC
I'm trying to evaluate Klaxon for possible use in my newsroom, and I've been seeing some weird behavior from the `check:all` Rake task: It sometimes detects too many changes (both the addition of content and its removal, at the same time) or ends up with a rollback in the middle of looking for changes. (Happy to split this up into two issues if you'd prefer.)

More details below. Would love to figure out what's going on here, because Klaxon does seem really useful!
## Change reversal

I tried tracking new posts on the home page of [Source](https://source.opennews.org/en-US/). (I think the selector was `body div#snap-content-wrapper.snap-content.overthrow div.content div.container article.homepage`.)

When I did this, I sometimes would get two emails at roughly the same time (i.e., not from separate `rake check:all` runs): One email with a new top post (and a corresponding post getting bumped to the next page), and another email with roughly the inverse of that change (i.e., the new top post being removed and the old bumped post coming back), and not necessarily in that order.

Two examples:
![klaxon-source-choochoobot](https://cloud.githubusercontent.com/assets/764865/14994041/be449952-113b-11e6-9dea-ac5e2cb3d724.png)
![klaxon-source-sheep](https://cloud.githubusercontent.com/assets/764865/14994042/be49e0a6-113b-11e6-8d67-a8de1bf71d6b.png)

These are weird, of course, because they aren't perfect inverses, but they seem to be happening at the same time regardless.

I don't have logs for these incidents, and since I've kept the scheduler task running, they're back beyond the 1,500-line maximum I can get from `heroku logs`.
## Unexplainable rollbacks

I also tried watching some subreddits and saw some odd notes in my Heroku logs (again, don't have those), so I decided to try to spin up the app on my laptop instead so I could more easily observe/control what's going on.

It turns out my selectors didn't work, so no changes were ever going to be detected (more details below), but oddly some pages never get that far and log something about rolling back some sort of database transaction:

```
$ bundle exec rake check:all
  AppSetting Exists (0.4ms)  SELECT  1 AS one FROM "app_settings" WHERE "app_settings"."key" = $1 LIMIT 1  [["key", "default_host"]]
  AppSetting Load (0.3ms)  SELECT  "app_settings".* FROM "app_settings" WHERE "app_settings"."key" = $1 LIMIT 1  [["key", "default_host"]]
setting default_host to localhost:5000
  Page Load (0.4ms)  SELECT "pages".* FROM "pages"
downloading url=https://www.reddit.com/r/dataisbeautiful/new/ for page.id=1
  PageSnapshot Load (0.8ms)  SELECT  "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."sha2_hash" = $1 AND "page_snapshots"."page_id" = 1 LIMIT 1  [["sha2_hash", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]]
   (0.2ms)  BEGIN
  SQL (0.3ms)  UPDATE "page_snapshots" SET "updated_at" = '2016-05-03 14:50:16.574080' WHERE "page_snapshots"."id" = $1  [["id", 1]]
   (0.4ms)  COMMIT
page 1 has not changed
downloading url=https://www.reddit.com/r/aww/new/ for page.id=2
  PageSnapshot Load (0.4ms)  SELECT  "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."sha2_hash" = $1 AND "page_snapshots"."page_id" = 2 LIMIT 1  [["sha2_hash", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"]]
   (0.1ms)  BEGIN
  PageSnapshot Exists (0.3ms)  SELECT  1 AS one FROM "page_snapshots" WHERE "page_snapshots"."sha2_hash" = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' LIMIT 1
   (0.5ms)  ROLLBACK
  Page Load (0.3ms)  SELECT "pages".* FROM "pages"
  PageSnapshot Load (0.3ms)  SELECT "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."page_id" = $1  [["page_id", 1]]
  PageSnapshot Load (0.3ms)  SELECT "page_snapshots".* FROM "page_snapshots" WHERE "page_snapshots"."page_id" = $1  [["page_id", 2]]
```

The page hashes shown in the logs here match the SHA-256 for an empty string, suggesting my selectors don't work for the pages as Klaxon downloaded them, which makes sense because my selectors (picked via the bookmarklet) suggest a logged-in user with Reddit Gold. (For /r/dataisbeautiful, I have `body.subscriber.listing-page.loggedin.gold.hot-page div.content div.spacer`, and for /r/aww, I have `body.subscriber.listing-page.loggedin.new-page.gold div.content div.spacer div#siteTable.sitetable.linklisting`.)

```
2.3.0 :001 > require "digest"
 => true
2.3.0 :002 > Digest::SHA256.hexdigest('')
 => "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
```

**Comment by ivarvong** [comment] 2016-05-03 19:37
Thanks for the detailed bug report! I'm excited that you're interested in the project, and the detail here is really helpful.

The multiple emails/changes is almost surely a bug in the "did something change?" calculation. (We separated the snapshotting from the diffing, so a hiccup in the former won't suppress notifications on the next run) I'll get this failure mode reproduced in a spec and update this issue.

Re: empty matches, we need better feedback mechanisms in the bookmarklet and in the webapp. We've got some in-progress work on that. If you have a way you feel like this should work, I'd love to chat about it. Empty match text is never what the user wants, of course, so we should flag this right away.

Anyway, both are on me and I'll fix 'em.

**Comment by tommeagher** [comment] 2016-05-04 16:09
Hey @myersjustinc, thanks so much for helping to kick the tires on Klaxon. This kind of feedback is super helpful as we continue development. At the moment, we're not quite finished with a release that is truly ready for users, but we hope to be there soon. We'll get issues like this buttoned up before we make that release public, and we hope you'll take another test of the system once it's production ready and give us some more thoughts on it then. 

Thanks again!

**Comment by myersjustinc** [comment] 2016-05-04 21:35
Thanks for the quick responses!

**Comment by rdmurphy** [comment] 2016-05-05 17:20
Just wanted to add — I've experienced this issue, too. Let's just say the multiple emails that do get sent when a change happens does a great job of getting my attention. 😜

**Comment by ivarvong** [comment] 2016-05-11 15:32
Actual work-in-progress branch for this: https://github.com/themarshallproject/klaxon/pull/22

**Comment by ivarvong** [comment] 2016-06-16 22:13
@myersjustinc I created a [stub server](https://github.com/themarshallproject/klaxon/blob/f63e8594925480279bd23209ecaf18682664e830/spec/support/fake_time_server.rb) to improve the [coverage](https://github.com/themarshallproject/klaxon/blob/f63e8594925480279bd23209ecaf18682664e830/spec/requests/change_spec.rb#L14-L30) on my (hopeful) fix for the multiple/out-of-order notifications. Hoping to get an [incremental release](https://github.com/themarshallproject/klaxon/pull/26) out tomorrow. Thanks for your patience.

**Comment by ivarvong** [comment] 2016-06-17 21:31
@myersjustinc @rdmurphy @tommeagher I just merged into `master` – please feel free to pull at your convenience and let me know it goes! Thanks!

**Comment by rdmurphy** [comment] 2016-06-17 23:22
Awesome! I'll try to get this pulled in over the weekend.

**Comment by myersjustinc** [comment] 2016-06-18 02:23
Thanks, @ivarvong! On vacation for a couple more days, but I'll take it for a spin when I'm back in the office.

**Comment by ivarvong** [comment] 2016-06-23 20:50
I caused a pretty major bug when merging this, which is now resolved in `master`.

**Comment by GabeIsman** [comment] 2017-01-20 20:54
This seems to be fixed. I couldn't reproduce the rollback issue that @myersjustinc identified, but it looks like just a side-effect of a rails optimization to me.

**Closed by GabeIsman** 2017-01-20 20:54 UTC
Labels: confirm fix
