### ISSUE TITLE
SendGrid account suspended by default

### ISSUE THREAD

**Issue by golfecholima** [themarshallproject/klaxon#268] opened 2019-05-06 14:20 UTC
At least two users have seen this happen out of the box after setting up Klaxon. Messaging SendGrip support seems to resolve the issue, but maybe a note to that effect could be added to the Klaxon instructions.

**Comment by GabeIsman** [comment] 2019-05-06 15:01
It's a good point @golfecholima. I've been meaning to find a more elegant solution, because this is a pain in the neck. I will add a note for now though!

Closing as a dupe of #238.

**Closed by GabeIsman** 2019-05-06 15:01 UTC
