### ISSUE TITLE
How to detect any change on page (no selector)?

### ISSUE THREAD

**Issue by tszumowski** [themarshallproject/klaxon#425] opened 2021-01-15 17:38 UTC
Is it possible to track for _any_ change on the page? I tried to keep the selector empty, but in the logs, I see entries like the following for any page that I left with no selector:

```
downloading url=https://(website) for page.id=4
2021-01-15T17:32:26.941141+00:00 app[scheduler.2842]: Failed to update page 4
```

**Comment by tszumowski** [comment] 2021-01-15 20:44
Hmm. Send this may be the same or similar to https://github.com/themarshallproject/klaxon/issues/155m
I'll leave this open to confirm.

**Comment by GabeIsman** [comment] 2021-01-15 21:10
@tszumowski Yep, this is definitely unintuitive behavior (and a duplicate of the bug you mentioned). If you just want to track the whole page putting `body` in the selector field should do the trick.

**Closed by GabeIsman** 2021-01-15 21:10 UTC

**Comment by tszumowski** [comment] 2021-01-15 22:22
@GabeIsman thank you for the quick reply and example usage!
