### ISSUE TITLE
Cached version of page not updating

### ISSUE THREAD

**Issue by jacksongs** [themarshallproject/klaxon#96] opened 2017-02-17 05:30 UTC
Hello,

I've run into a problem since upgrading to 0.2 (master branch).

I am being alerted to the same change every scraper run (every 10 minutes) until I edit the page on in the admin interface.

Every change detected has suffered from this problem (4 so far this week).

Each email says "It has changed 1 times since Klaxon started monitoring it on".

Any suggestions for how to troubleshoot?

**Comment by tommeagher** [comment] 2017-02-17 12:23
Jackson, thanks for filing this issue. We've gotten a similar report from
another user. This sounds like a bug we should investigate. We'll look into
it, and if we need more info from you, we'll holler.
-- 
Tom Meagher
Deputy Managing Editor, The Marshall Project
<http://www.themarshallproject.org/>
PGP Public key
<https://themarshallproject-gpg.s3.amazonaws.com/tmeagher.asc>

**Comment by GabeIsman** [comment] 2017-02-23 15:59
Hey @jacksongs, thanks for the bug report and sorry for the trouble you're having. I've spent some time digging into this and trying to reproduce it, but haven't been able to. I have some theories though. This would happen if the sending of notifications fails for some reason. A recent change (https://github.com/themarshallproject/klaxon/commit/8222f6b20cf20db1511887853174a20fd75f33fe) should make this significantly less likely, but that's not yet in the master branch. Can you provide me with a little more information?

1) Are you using the heroku web UI only deploy workflow described in the readme? I just realized there is an oversight in the documentation for upgrading that could lead to consistent errors in sending notifications.

2) Does the problem recur on the next change after you've edited the page? Or does editing the page permanently resolve the problem for that page?

Thanks for the info!

**Comment by jacksongs** [comment] 2017-02-24 07:08
Hi there, 

Yes, I can imagine it's a difficult one to reproduce. I'm considering moving to a fresh 0.2 install. Let me know if there's anything I can pull out of the heroku machine - I'm still getting my head around the Klaxon architecture.

1. Yes, used the web UI upgrade method in the docs.
2. I removed the selector for the pages in question (assuming it would monitor the whole page), and I have not received any more alerts. I suspect having no selector means no content is monitored - can you confirm?

**Comment by GabeIsman** [comment] 2017-02-24 16:27
Moving to a fresh install should resolve the problem, but I think there's a less nuclear option as well. 

Removing the selector does mean that no content is monitored (it seems as though this actually just causes the polling task to fail due to a css syntax error, an oddity of the library we are using).

Can you try something for me? I suspect that the spam notification behavior you were getting was due to a migration (a task that updates the database to a new schema) that hasn't been run. This totally our fault for not including this step in the documentation, so apologies for causing you this trouble! The remedy is as follows:

### If you are familiar with the command line

1. Get set up with [Heroku CLI tools](https://devcenter.heroku.com/articles/heroku-cli) if you haven't already.
2. When you've run `heroku login` you just need to run `heroku run rake db:migrate`. If you have multiple heroku apps you may need to run `heroku run rake db:migrate -a <klaxon-app-name>`.
3. Note that you may want to follow the instructions below as well, to make this process automatic on each deploy.

### Through the web UI

We have updated the default Heroku configuration so new installations going forward won't suffer from this issue, but if you've already deployed Klaxon that won't help you. To make sure migrations get run after each deploy, follow these steps.

1. Go into the 'Settings' tab for the klaxon app on dashboard.heroku.com.
2. In the 'Buildpacks' section click on 'Add Buildpack'
3. Enter `https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks` into the text box that pops up and click 'Save Changes'.
4. In the 'Config Variables' section click on 'Reveal Config Vars'. 
5. In the empty text boxes at the bottom, enter `DEPLOY_TASKS` on the left and `db:migrate` on the right. Click 'Add'.
6. To actually run the migration trigger a manual deploy from the bottom of the 'Deploy' tab by clicking 'Deploy Branch'. The line
   ```
   ActiveRecord::SchemaMigration Load (0.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
   ```
   should appear in the build log. If you have pending migrations, this will be followed by the log   output for them as well.
7. That's it, you should be all set going forward.

Please let me know if this solves your issue!

Thanks,
Gabe

**Comment by tommeagher** [comment] 2017-03-14 19:16
Hey @jacksongs, was this migration able to solve your issue?

**Comment by jacksongs** [comment] 2017-03-16 07:48
Hi Tom, I've been getting other alerts in the usual fashion, so it appears
to be fixed. I will keep you updated if it changes.

**Comment by tommeagher** [comment] 2017-03-16 13:36
Great. I'll close this for now. If you see any other problems pop up, let us know and we can re-open this.

**Closed by tommeagher** 2017-03-16 13:36 UTC
