### ISSUE TITLE
Unable to watch a Github organization

### ISSUE THREAD

**Issue by jarib** [themarshallproject/klaxon#93] opened 2017-02-09 22:30 UTC
I tried adding a Github organization page, which lead to this error being logged:

Refused to load the script 'https://[my-app-name].herokuapp.com/embed/inject' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com"

**Comment by tommeagher** [comment] 2017-02-10 21:38
Thanks for flagging this, @jarib. I believe this is related to issue #84, which we recently discovered on Twitter. For now, I think you can add an alert manually with the appropriate CSS selector if you go to ```your-klaxon-domain-here.com/watching/pages/new```.

I'll close this issue now as a duplicate of #84, but we'll think about how to make that easier to navigate with the bookmarklet.

**Closed by tommeagher** 2017-02-10 21:38 UTC
Labels: duplicate
