### ISSUE TITLE
feature request: track changes on an online pdf file

### ISSUE THREAD

**Issue by bobweston** [themarshallproject/klaxon#240] opened 2019-02-11 18:28 UTC
We're seeing a growing number of sites posting information to online pdf files. We're wondering if there are plans to allow users to detect if a pdf file posted for online viewing has been updated.

**Comment by tommeagher** [comment] 2019-02-11 19:53
Hey @bobweston, it's great to hear from you. That was actually a feature of a previous incarnation of Klaxon, and one that we've long hoped to bring into the modern version of the project. I think it's tracked in #43. I'll close this one as a duplicate of that earlier ticket, but if you have thoughts on what you'd like to see or how it would be useful for your users, we'd love to hear it there.

In the past version, it merely notified you if a file at a URL changed. It didn't matter if the file was a PDF or a CSV or something else. It didn't offer a diff of the changes, but was helpful nonetheless, and that's kind of what we had in mind for the future in #43.

**Closed by tommeagher** 2019-02-11 19:53 UTC
Labels: duplicate
